<template>
    <div id="main">
        <InputText id="nameInput" v-model="name" placeholder="Enter name" />
        <br />
        <p>
            Upload a config file generated by the ESP32:</p>
        <FileUpload mode="basic" chooseLabel="Choose" accept=".json" @select="handleFileUpload" :auto="true" />
        <Button label="Submit" @click="submitData" />
    </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import InputText from 'primevue/inputtext';
import FileUpload from 'primevue/fileupload';
import Button from 'primevue/button';
import { data_from_esp } from '@/types';
import axiosService from "@/services/axiosService";
import { usePanelStore } from '@/stores/panelStore';
const emit = defineEmits(['hide']);
const panelStore = usePanelStore();
const name = ref('');
const jsonData = ref<data_from_esp>({
    deveui: null,
    appeui: null,
    appkey: null
});

function handleFileUpload(event: any) {
    // const file = event.files[0];
    // if (file) {
    //     const reader = new FileReader();
    //     reader.readAsText(file);
    //     reader.onload = () => {
    //         try {
    //             jsonData.value = JSON.parse(reader.result as string);
    //         } catch (e) {
    //             alert('Error parsing JSON file.');
    //         }
    //     };
    // }
    const files = event.files; // event.currentFiles for some PrimeVue versions
    if (files && files[0]) {
        const file = files[0];
        const reader = new FileReader();
        reader.readAsText(file);
        reader.onload = () => {
            try {
                jsonData.value = JSON.parse(reader.result as string);
            } catch (e) {
                console.error('Error parsing JSON file: ', e);
                alert('Error parsing JSON file.');
            }
        };
        reader.onerror = (e) => {
            console.error('Error reading file: ', e);
            alert('Error reading file.');
        };
    }
}

async function submitData() {
    if (jsonData.value.deveui && jsonData.value.appeui && jsonData.value.appkey) {
        axiosService().post('/AddPanel', {
            name: name.value,
            deveui: jsonData.value.deveui,
            joineui: jsonData.value.appeui,
            appkey: jsonData.value.appkey
        }).then(() => {
            panelStore.LoadPanels();
            emit('hide');
            alert('Panel added succesfully!');
        }).catch((error: any) => {
            alert('Error submitting data: ' + error.message);
        });
    } else {
        alert('Please upload a valid JSON file.');
    }
}
</script>
<style scoped>
div#main {
    margin: 1vw;

}

div#main>* {
    margin-bottom: 1vw;
}
</style>